[package]
name = "rocket_app"
version = "0.1.0"
edition = "2021"
authors = ["Matthew Oduamafu <mattoduamafu@gmail.com>"]

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
serde_json = "1.0.128"